%{
plot3(NormTime, repmat(strainIncrement,1,57046),  strainProf)
hold
scatter3(NormTime, repmat(xLocation(1,2),57046,1), (10^-6)*offset(sg(:,1)))
scatter3(NormTime, repmat(xLocation(2,2),57046,1), (10^-6)*offset(sg(:,2)))
scatter3(NormTime, repmat(xLocation(3,2),57046,1), (10^-6)*offset(sg(:,3)))
scatter3(NormTime, repmat(xLocation(4,2),57046,1), (10^-6)*offset(sg(:,4)))
%}
if ProcessOutputPlots == true
    r1 = 1;
    r2 = length(sg);
    %Check if folder to save these in exists and create folder if it doesnt
    fullPathName = fullfile(ProcessFilePath,ProcessCodeName);
    if exist(fullPathName,'dir') == 0
        mkdir(ProcessFilePath,ProcessCodeName);
    end
    
    %Put SVG and PNG files into seperate folders to help with clutter
    if exist(fullfile(fullPathName,'SVG'),'dir') == 0
        mkdir(fullPathName,'SVG');
    end
    
    if exist(fullfile(fullPathName,'PNG'),'dir') == 0
        mkdir(fullPathName,'PNG');
    end
    
    %Confirm that all of the folders exist
    if any([exist(fullPathName,'dir'), ...
       exist(fullfile(fullPathName,'SVG'),'dir'), ...
       exist(fullfile(fullPathName,'PNG'),'dir')]) == 0 ...
       
       error('Can not create plots due inability to create directories.');
    end
        
    %Strain gauge array positions change depending on shear tab. this
    %assures that the correct column strain gauges are plotted as desired.
    if ProcessShearTab == '2' || ProcessShearTab == '4'
        plotArrayCol = [offset(sg(r1:r2,7)) offset(sg(r1:r2,8)) offset(sg(r1:r2,9)) offset(sg(r1:r2,10))];
        strainBolt   = sg(r1:r2,5);
    else
        plotArrayCol = [offset(sg(r1:r2,6)) offset(sg(r1:r2,7)) offset(sg(r1:r2,8)) offset(sg(r1:r2,9))];
        strainBolt   = sg(r1:r2,4);
    end

    %%%% Strain Gauges %%%%
    disp('Plotting strain gauge data');
    smartPlot(NormTime(r1:r2), [sg(r1:r2,1) sg(r1:r2,2) sg(r1:r2,3) sg(r1:r2,4)], ...
        'Strain Gauge Data on Shear Tab', 'Time (sec)', 'Strain (uStrain)', ...
        'legend', {'SG1','SG2','SG3','SG4'}, 'visible', 'grid', 'save', 'sg-st');
    
    smartPlot(NormTime(r1:r2), strainBolt, ...
        'Strain Gauge Instrumented Bolt', 'Time (sec)', 'Strain (uStrain)', ...
        'visible', 'grid', 'save', 'sg-bolt');
    
    smartPlot(NormTime(r1:r2), [offset(sg(r1:r2,1)) offset(sg(r1:r2,2)) offset(sg(r1:r2,3)) offset(sg(r1:r2,4))], ...
        'Offset Strain Gauge Data on Shear Tab', 'Time (sec)', 'Strain (uStrain)', ...
        'legend', {'SG1','SG2','SG3','SG4'}, 'visible', 'grid', 'save', 'sg-st-offset');
    
    smartPlot(NormTime(r1:r2), plotArrayCol, ...
        'Offset Column Strain Gauges', 'Time (sec)', 'Strain (uStrain)', ...
        'legend', {'SG19','SG20','SG21','SG22'}, 'visible', 'grid', 'save', 'sg-col-offset');
    
    %%%% Load Cells %%%%
    disp('Plotting load cell data');
    smartPlot(NormTime(r1:r2), [lc(r1:r2,1) lc(r1:r2,2) lc(r1:r2,3) lc(r1:r2,4)], ...
        'Reaction Block Load Cells', 'Time (sec)', 'Force (lbf)', ...
        'legend', {'LC1','LC2','LC3','LC4'}, 'grid', 'visible', 'save', 'lc');
    
    smartPlot(NormTime(r1:r2), [offset(lc(r1:r2,1)) offset(lc(r1:r2,2)) offset(lc(r1:r2,3)) offset(lc(r1:r2,4))], ...
        'Offset Reaction Block Load Cells', 'Time (sec)', 'Force (lbf)', ...
        'legend', {'LC1','LC2','LC3','LC4'}, 'visible', 'grid', 'save' ,'lc-offset');
    
    smartPlot(NormTime(r1:r2), [offset(lc(r1:r2,1)) offset(lc(r1:r2,2)) offset(lc(r1:r2,3)) offset(lc(r1:r2,4)), offset(lc(r1:r2,5))], ...
        'Offset All Load Cells', 'Time (sec)', 'Force (lbf)', ...
        'legend', {'LC1','LC2','LC3','LC4','MTSLC'}, 'visible', 'grid', 'save', 'lc-all-offset');
    
    smartPlot(NormTime(r1:r2), offset(lc(r1:r2,5)), ...
        'Offset Actuator LC', 'Time (sec)', 'Force (lbf)', 'visible', ...
        'grid', 'save', 'lc-actuator-offset');
    
    smartPlot(NormTime(r1:r2), [offset(lc(r1:r2,6)) offset(lc(r1:r2,7))], ...
        'Offset Rxn Block Load Cell Groups', 'Time (sec)', 'Force (lbf)', ...
        'legend', {'LC G1','LC G2'}, 'visible', 'grid', 'save', 'lc-groups-offset');
    
    %%%% Angles %%%%
    disp('Plotting rotation data');
    smartPlot(NormTime(r1:r2), beamRotation(r1:r2,1), 'WP Group 1 Top Rotation (Init. Angles)', ...
        'Time (sec)', 'Rotation (rad)', 'grid', 'visible', 'save', ...
        'rotation-1g11-offset');
    
    smartPlot(NormTime(r1:r2), beamRotation(r1:r2,5), 'WP Group 1 Bot Rotation (Init. Angles)', ...
        'Time (sec)', 'Rotation (rad)', 'grid', 'visible', 'save', ...
        'rotation-1g12-offset');
    
    smartPlot(NormTime(r1:r2), beamRotation(r1:r2,2), 'WP Group 2 Top Rotation (Init. Angles)', ...
        'Time (sec)', 'Rotation (rad)', 'grid', 'visible', 'save', ...
        'rotation-1g21-offset');
    
    smartPlot(NormTime(r1:r2), beamRotation(r1:r2,6), 'WP Group 2 Bot Rotation (Init. Angles)', ...
        'Time (sec)', 'Rotation (rad)', 'grid', 'visible', 'save', ...
        'rotation-1g22-offset');
    
    smartPlot(NormTime(r1:r2), [beamRotation(r1:r2,1), beamRotation(r1:r2,2)], ...
        'WP Group 1&2 Top Rotation (Init. Angles)', 'Time (sec)', 'Rotation (rad)', ...
        'legend', {'WPG1T','WPG2T'}, 'grid', 'visible', 'save', ...
        'rotation-1g121-offset');
    
    smartPlot(NormTime(r1:r2), [beamRotation(r1:r2,5), beamRotation(r1:r2,6)], ...
        'WP Group 1&2 Bot Rotation (Init. Angles)', 'Time (sec)', 'Rotation (rad)', ...
        'legend', {'WPG1B','WPG2B'},  'grid', 'visible', 'save', ...
        'rotation-1g122-offset')
    
    smartPlot(NormTime(r1:r2), [beamRotation(r1:r2,1), beamRotation(r1:r2,5), ...
        beamRotation(r1:r2,2), beamRotation(r1:r2,6)], ...
        'All WP Groups (Init. Angles)', 'Time (sec)', 'Rotation (rad)', ...
        'legend', {'WPG1T', 'WPG1B', 'WPG2T', 'WPG2B'}, 'grid', 'visible', 'save', ...
        'rotation-1gA-offset');
    
    smartPlot(NormTime(r1:r2), beamRotation(r1:r2,6), 'WP Group 1 Top Rotation (Median)', ...
        'Time (sec)', 'Rotation (rad)', 'grid', 'visible', 'save', ...
        'rotation-2g11-offset');
    
    smartPlot(NormTime(r1:r2), beamRotation(r1:r2,9), 'WP Group 1 Bot Rotation (Median)', ...
        'Time (sec)', 'Rotation (rad)', 'grid', 'visible', 'save', ...
        'rotation-2g12-offset');
    
    smartPlot(NormTime(r1:r2), beamRotation(r1:r2,7), 'WP Group 2 Top Rotation (Median)', ...
        'Time (sec)', 'Rotation (rad)', 'grid', 'visible', 'save', ...
        'rotation-2g21-offset');
    
    smartPlot(NormTime(r1:r2), beamRotation(r1:r2,10), 'WP Group 2 Bot Rotation (Median)', ...
        'Time (sec)', 'Rotation (rad)', 'grid', 'visible', 'save', ...
        'rotation-2g22-offset');
    
    smartPlot(NormTime(r1:r2), [beamRotation(r1:r2,6), beamRotation(r1:r2,7)], ...
        'WP Group 1&2 Top Rotation (Median)', 'Time (sec)', 'Rotation (rad)', ...
        'legend', {'WPG1T','WPG2T'}, 'grid', 'visible', 'save', ...
        'rotation-2g121-offset');
    
    smartPlot(NormTime(r1:r2), [beamRotation(r1:r2,9), beamRotation(r1:r2,10)], ...
        'WP Group 1&2 Bot Rotation (Median)', 'Time (sec)', 'Rotation (rad)', ...
        'legend', {'WPG1B','WPG2B'}, 'grid', 'visible', 'save', ...
        'rotation-2g122-offset')
    
    smartPlot(NormTime(r1:r2), [beamRotation(r1:r2,6), beamRotation(r1:r2,9), ...
        beamRotation(r1:r2,7), beamRotation(r1:r2,10)], ...
        'All WP Groups (Median)', 'Time (sec)', 'Rotation (rad)', ...
        'legend', {'WPG1T', 'WPG1B', 'WPG2T', 'WPG2B'}, 'grid', 'visible', ...
        'save', 'rotation-2gA-offset');
    
    smartPlot(NormTime(r1:r2), beamRotation(r1:r2,11), 'WP Group 1&2 Top Rotation (Vector)', ...
        'Time (sec)', 'Rotation (rad)', 'grid', 'visible', 'save', ...
        'rotation-3g1-offset');
    
    smartPlot(NormTime(r1:r2), beamRotation(r1:r2,12), 'WP Group 1&2 Bot Rotation (Vector)', ...
        'Time (sec)', 'Rotation (rad)', 'grid', 'visible', 'save', ...
        'rotation-3g2-offset');
    
    smartPlot(NormTime(r1:r2), [beamRotation(r1:r2,11), beamRotation(r1:r2,12)], ...
        'All WP Groups (Vector)', 'Time (sec)', 'Rotation (rad)', ...
        'legend', {'WPT', 'WPB'}, 'grid', 'visible', ...
        'save', 'rotation-3gA-offset');
    
    smartPlot(NormTime(r1:r2), beamRotation(r1:r2,13), 'WP Group 1&2 Top Rotation (Horn)', ...
        'Time (sec)', 'Rotation (rad)', 'grid', 'visible', 'save', ...
        'rotation-4g1-offset');
    
    smartPlot(NormTime(r1:r2), beamRotation(r1:r2,14), 'WP Group 1&2 Bot Rotation (Horn)', ...
        'Time (sec)', 'Rotation (rad)', 'grid', 'visible', 'save', ...
        'rotation-3g2-offset');
    
    smartPlot(NormTime(r1:r2), [beamRotation(r1:r2,13), beamRotation(r1:r2,14)], ...
        'All WP Groups (Horn)', 'Time (sec)', 'Rotation (rad)', ...
        'legend', {'WPT', 'WPB'}, 'grid', 'visible', ...
        'save', 'rotation-4gA-offset');
    
    smartPlot(NormTime(r1:r2), beamRotation(r1:r2,3), 'WP Group 3 Rotation (Init. Angle)', ...
        'Time (sec)', 'Rotation (rad)', 'grid', 'visible', 'save', ...
        'rotation-1g3-offset');
    
    smartPlot(NormTime(r1:r2), beamRotation(r1:r2,8), 'WP Group 3 Rotation (Median)', ...
        'Time (sec)', 'Rotation (rad)', 'grid', 'visible', 'save', ...
        'rotation-2g3-offset');
    
    %%%% Wire-pots %%%%
    disp('Plotting wire-pot data');
    smartPlot(NormTime(r1:r2), [offset(wp(r1:r2,7)) offset(wp(r1:r2,3)) offset(wp(r1:r2,1)) offset(wp(r1:r2,12))], ...
        'Offset Wirepot Group 1', 'Time (sec)', 'Length (in)', ...
        'legend', {'WP4-1','WP2-1','WP1-1','WP7-1'},  'visible', 'grid', 'save', 'wp-g1-offset');
    
    smartPlot(NormTime(r1:r2), [offset(wp(r1:r2,8)) offset(wp(r1:r2,4)) offset(wp(r1:r2,2)) offset(wp(r1:r2,13))], ...
        'Offset Wirepot Group 2', 'Time (sec)', 'Length (in)', ...
        'legend', {'WP4-2','WP2-2','WP1-2','WP7-2'}, 'visible', 'grid', 'save', 'wp-g2-offset');
    
    smartPlot(NormTime(r1:r2), [offset(wp(r1:r2,1)) offset(wp(r1:r2,2))], ...
        'Offset Vertical Wirepots', 'Time (sec)', 'Length (in)', ...
        'legend', {'WP1-1','WP1-2'}, 'visible', 'grid', 'save', 'wp-vert-offset');
    
    smartPlot(NormTime(r1:r2), [offset(wp(r1:r2,7)) offset(wp(r1:r2,8))], ...
        'Offset Horizontal Wirepots (Top Flange)', 'Time (sec)', 'Length (in)', ...
        'legend', {'WP4-1','WP4-2'}, 'visible', 'grid', 'save', 'wp-horztop-offset');
    
    smartPlot(NormTime(r1:r2), [offset(wp(r1:r2,3)) offset(wp(r1:r2,4))], ...
        'Offset Horizontal Wirepots (Bottom Flange)', 'Time (sec)', 'Length (in)', ...
        'legend', {'WP2-1','WP2-2'}, 'visible', 'grid', 'save', 'wp-horzbot-offset');
    
    smartPlot(NormTime(r1:r2), [offset(wp(r1:r2,7)) offset(wp(r1:r2,3)) offset(wp(r1:r2,1)) ...
        offset(wp(r1:r2,8)) offset(wp(r1:r2,4)) offset(wp(r1:r2,2)) offset(wp(r1:r2,12)) offset(wp(r1:r2,13))], ...
        'Offset All Beam Rotation Wirepots', 'Time (sec)', 'Length (in)', ...
        'legend', {'WP4-1','WP2-1','WP1-1','WP4-2','WP2-2','WP1-2','WP7-1','WP7-2'}, ...
        'visible', 'grid', 'save', 'wp-allrot-offset');
    
    smartPlot(NormTime(r1:r2), [offset(wp(r1:r2,10)) offset(wp(r1:r2,11))], ...
        'Offset Wirepots Measuring Twist in Column', 'Time (sec)', 'Length (in)', ...
        'legend', {'WP6-1','WP6-2'}, 'visible', 'grid', 'save', 'wp-twist-offset');
    
    %%%% Linear Potentiometers %%%%
    disp('Plotting linear potentiometer data');
    smartPlot(NormTime(r1:r2), offset(lpValues1(r1:r2,end)), ...
        'Offset Linear Potentiometer 1', 'Distance (in.)', ...
        'Time (Sec.)', 'visible', 'grid', 'save', 'lp-1-offset');
    
    smartPlot(NormTime(r1:r2), offset(lpValues2(r1:r2,end)), ...
        'Offset Linear Potentiometer 2', 'Distance (in.)', ...
        'Time (Sec.)', 'visible', 'grid', 'save', 'lp-2-offset');
    
    smartPlot(NormTime(r1:r2), offset(lpValues3(r1:r2,end)), ...
        'Offset Linear Potentiometer 3', 'Distance (in.)', ...
        'Time (Sec.)', 'visible', 'grid', 'save', 'lp-3-offset');
    
    smartPlot(NormTime(r1:r2), offset(lpValues4(r1:r2,end)), ...
        'Offset Linear Potentiometer 4', 'Distance (in.)', ...
        'Time (Sec.)', 'visible', 'grid', 'save', 'lp-4-offset');
    
    smartPlot(NormTime(r1:r2), [offset(lpValues1(r1:r2,end)) offset(lpValues2(r1:r2,end))], ...
        'Offset Linear Potentiometer 1 & 2', 'Time (sec)', 'Length (in)', ...
        'legend', {'LP1','LP2'}, 'visible', 'grid', 'save', 'lp-12-offset');
    
    smartPlot(NormTime(r1:r2), [offset(lpValues3(r1:r2,end)) offset(lpValues4(r1:r2,end))], ...
        'Offset Linear Potentiometer 3 & 4', 'Time (sec)', 'Length (in)', ...
        'legend', {'LP3','LP4'}, 'visible', 'grid', 'save', 'lp-34-offset');
    
    smartPlot(NormTime(r1:r2), [offset(lpValues1(r1:r2,end)) offset(lpValues3(r1:r2,end))], ...
        'Offset Linear Potentiometer 1 & 3', 'Time (sec)', 'Length (in)', ...
        'legend', {'LP1','LP3'}, 'visible', 'grid', 'save', 'lp-13-offset');
    
    smartPlot(NormTime(r1:r2), [offset(lpValues2(r1:r2,end)) offset(lpValues4(r1:r2,end))], ...
        'Offset Linear Potentiometer 2 & 4', 'Time (sec)', 'Length (in)', ...
        'legend', {'LP2','LP4'}, 'visible', 'grid', 'save', 'lp-24-offset');
    
    smartPlot(NormTime(r1:r2), [offset(lp(r1:r2,5)) offset(lp(r1:r2,6))], ...
        'Offset Linear Potentiometer Averages', 'Time (sec)', 'Length (in)', ...
        'legend', {'LP1&2','LP3&4'}, 'visible', 'grid', 'save', 'lp-avg-offset');
    
    smartPlot(NormTime(r1:r2), [offset(lpValues1(r1:r2,end)) offset(lpValues2(r1:r2,end)) offset(lpValues1(r1:r2,end)) offset(lpValues2(r1:r2,end))], ...
        'Offset Linear Potentiometer 2 & 4', 'Time (sec)', 'Length (in)', ...
        'legend', {'LP1','LP2','LP3','LP4'}, 'visible', 'grid', 'save', 'lp-all-offset');
    
    %%%% Hysteresis Using Modified Moment %%%%
    disp('Plotting modified moment hysteresis data');
    smartPlot(beamRotation(r1:r2,1), moment(r1:r2,7), ...
        'Offset Hysteresis - WP Group 1 (Top) (Init. Angle)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-1g11-offset');
    
    smartPlot(beamRotation(r1:r2,4), moment(r1:r2,7), ...
        'Offset Hysteresis - WP Group 1 (Bot) (Init. Angle)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-1g12-offset');
    
    smartPlot(beamRotation(r1:r2,2), moment(r1:r2,7), ...
        'Offset Hysteresis - WP Group 2 (Top) (Init. Angle)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-1g21-offset');
    
    smartPlot(beamRotation(r1:r2,5), moment(r1:r2,7), ...
        'Offset Hysteresis - WP Group 2 (Bot) (Init. Angle)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-1g22-offset');
    
    smartPlot(beamRotation(r1:r2,6), moment(r1:r2,7), ...
        'Offset Hysteresis - WP Group 1 (Top) (Median)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-2g11-offset');
    
    smartPlot(beamRotation(r1:r2,9), moment(r1:r2,7), ...
        'Offset Hysteresis - WP Group 1 (Bot) (Median)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-2g12-offset');
    
    smartPlot(beamRotation(r1:r2,7), moment(r1:r2,7), ...
        'Offset Hysteresis - WP Group 2 (Top) (Median)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-2g21-offset');
    
    smartPlot(beamRotation(r1:r2,10), moment(r1:r2,7), ...
        'Offset Hysteresis - WP Group 2 (Bot) (Median)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-2g22-offset');
    
    smartPlot(beamRotation(r1:r2,11), moment(r1:r2,7), ...
        'Offset Hysteresis - WP Group 1&2 (Top) (Vector)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-3g1-offset');
    
    smartPlot(beamRotation(r1:r2,12), moment(r1:r2,7), ...
        'Offset Hysteresis - WP Group 1&2 (Bot) (Vector)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-3g2-offset');
    
    smartPlot(beamRotation(r1:r2,13), moment(r1:r2,7), ...
        'Offset Hysteresis - WP Group 1&2 (Top) (Horn)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-4g1-offset');
    
    smartPlot(beamRotation(r1:r2,14), moment(r1:r2,7), ...
        'Offset Hysteresis - WP Group 1&2 (Bot) (Horn)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-4g2-offset');
    
    smartPlot(beamRotation(r1:r2,3), moment(r1:r2,7), ...
        'Offset Hysteresis - WP Group 3 (Init. Angle)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-1g3-offset');
    
    smartPlot(beamRotation(r1:r2,8), moment(r1:r2,7), ...
        'Offset Hysteresis - WP Group 3 (Median)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-2g3-offset');
    
    %%%% Hysteresis Using Un-Modified Moment %%%%
    disp('Plotting unmodified moment hysteresis data');
    smartPlot(beamRotation(r1:r2,1), moment(r1:r2,6), ...
        'Offset Hysteresis - Unmod - WP Group 1 (Top) (Init. Angle)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-u1g11-offset');
    
    smartPlot(beamRotation(r1:r2,4), moment(r1:r2,6), ...
        'Offset Hysteresis - Unmod - WP Group 1 (Bot) (Init. Angle)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-u1g12-offset');
    
    smartPlot(beamRotation(r1:r2,2), moment(r1:r2,6), ...
        'Offset Hysteresis - Unmod - WP Group 2 (Top) (Init. Angle)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-u1g21-offset');
    
    smartPlot(beamRotation(r1:r2,5), moment(r1:r2,6), ...
        'Offset Hysteresis - Unmod - WP Group 2 (Bot) (Init. Angle)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-u1g22-offset');
    
    smartPlot(beamRotation(r1:r2,6), moment(r1:r2,6), ...
        'Offset Hysteresis - Unmod - WP Group 1 (Top) (Median)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-u2g11-offset');
    
    smartPlot(beamRotation(r1:r2,9), moment(r1:r2,6), ...
        'Offset Hysteresis - Unmod - WP Group 1 (Bot) (Median)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-u2g12-offset');
    
    smartPlot(beamRotation(r1:r2,7), moment(r1:r2,6), ...
        'Offset Hysteresis - Unmod - WP Group 2 (Top) (Median)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-u2g21-offset');
    
    smartPlot(beamRotation(r1:r2,10), moment(r1:r2,6), ...
        'Offset Hysteresis - Unmod - WP Group 2 (Bot) (Median)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-u2g22-offset');
    
    smartPlot(beamRotation(r1:r2,11), moment(r1:r2,6), ...
        'Offset Hysteresis - Unmod - WP Group 1&2 (Top) (Vector)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-u3g1-offset');
    
    smartPlot(beamRotation(r1:r2,12), moment(r1:r2,6), ...
        'Offset Hysteresis - Unmod - WP Group 1&2 (Bot) (Vector)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-u3g2-offset');
    
    smartPlot(beamRotation(r1:r2,13), moment(r1:r2,6), ...
        'Offset Hysteresis - Unmod - WP Group 1&2 (Top) (Horn)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-u4g1-offset');
    
    smartPlot(beamRotation(r1:r2,14), moment(r1:r2,6), ...
        'Offset Hysteresis - Unmod - WP Group 1&2 (Bot) (Horn)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-u4g2-offset');
    
    smartPlot(beamRotation(r1:r2,3), moment(r1:r2,6), ...
        'Offset Hysteresis - Unmod - WP Group 3 (Init. Angle)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-u1g3-offset');
    
    smartPlot(beamRotation(r1:r2,8), moment(r1:r2,6), ...
        'Offset Hysteresis - Unmod - WP Group 3 (Median)', 'Rotation (rad)', ...
        'Moment (lbf-in)', 'visible', 'grid', 'save', 'hyst-u2g3-offset');

end